[package]
name = "fshuf"
version = "0.2.1"
authors = [ "k4rakara <jack@insertdomain.name>" ]
edition = "2018"
build = "src/build.rs"

[dependencies]
rand = "0.7.3"
regex = "1.3.9"

[build-dependencies]
clml_rs = { git = "https://github.com/K4rakara/clml-rs" }


